# Check https://circleci.com/docs/2.0/language-java/ for more details
# 关于circleci的设置：https://www.testcontainers.org/supported_docker_environment/continuous_integration/circle_ci/
version: 2
executorType: machine
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01    # pins image to specific version
    steps:
      - checkout

      - run:
          name: Install prerequists
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk maven
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-11.0.5/bin/java 1
            sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-11.0.5/bin/javac 1
            echo 'export JAVA_HOME=/usr/local/openjdk-11.0.2_linux-x64_bin/jdk-11.0.2
                  export JRE_HOME=$JAVA_HOME/jre
                  export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
                  export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH' > ~/.profile
      - run:
          name: Maven install
          command: |
            . ~/.profile
            mvn -B clean install
