# Check https://circleci.com/docs/2.0/language-java/ for more details
# 关于circleci的设置：https://www.testcontainers.org/supported_docker_environment/continuous_integration/circle_ci/
version: 2
executorType: machine
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01    # pins image to specific version
    steps:
      - checkout

      - run:
          name: Clean old java
          command: |
            sudo update-binfmts --package openjdk-8 --remove jar /usr/bin/jexec

      - run:
          name: Install prerequists
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk maven

      - run:
          name: Maven install
          command: |
            which java
#            sudo update-binfmts --package openjdk-11 --install jar /usr/bin/jexec --magic PK\x03\x04
#            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-11.0.5/bin/java 1
#            sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-11.0.5/bin/javac 1
            java -version
            mvn -B clean install
