# Check https://circleci.com/docs/2.0/language-java/ for more details
# 关于circleci的设置：https://www.testcontainers.org/supported_docker_environment/continuous_integration/circle_ci/
version: 2.1
executorType: machine
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01    # pins image to specific version
    steps:
      - checkout
      - run:
          name: Maven install
          command: |
            mvn -B clean install
